### ISSUE TITLE
Missing stylesheet in Lists page

### ISSUE THREAD

**Issue by jumpjack** [ehdorrii/idsky#1]
https://github.com/ehdorrii/idsky/blob/dfcb874625c6c10ccb4861c0fd12ecde490aea46/listIndex.html#L4

Missing line in head section:
`    <link rel="stylesheet" type="text/css"  href="css/iDSKY.css">`

It works anyway, but not if open as a standalone page.

**Comment by ehdorrii** [comment]
That page (and all the "demoXxxx", "helpXxxx" and "listXxxx" html) was never intended to be standalone: they are all part of the iDSKY package.
